### ISSUE TITLE
Missing Diagonal Wall Feature

### ISSUE THREAD

**Issue by jkker** [Riju19/Evasion-Game#3]
Hi Architects,

The [description for the Evasion game](https://cs.nyu.edu/courses/fall22/CSCI-GA.2965-001/evasion.html) reads:

> The wall must be vertical or horizontal or diagonal or counter-diagonal (the last two are new for 2017) and must touch neither H nor P nor go through another wall (though it may touch another wall). That is, a wall that would hit P if built is not built. The diagonal and counter-diagonal wall are two units thick, so they occupy for example (i,j), (i,j+1), (i+1,j+1), (i+1,j+2). 

However, the only relatable thing I see here is [commit 51e8df](https://github.com/Riju19/Evasion-Game/commit/51e8dfad136aafffb2ba3594c7b57cb38b401653), which removed such implementation. Would you please explain how we should go about this?

**Comment by Riju19** [comment]
Hi, 
As Professor mentioned in class, we will not be having diagonal walls for this game. I think the game description has not been updated yet.

**Comment by jkker** [comment]
Thanks
