### ISSUE TITLE
No Input Validation

### ISSUE THREAD

**Issue by jkker** [Riju19/Evasion-Game#4]
The game server currently does no validation for user inputs. E.g. prey agent requesting to move +300,+300 in one game tick is accepted and registered.

**Comment by Riju19** [comment]
Prey movement here means the prey’s velocity. So it will essentially only be checking the signs of the numbers. Hence putting x = 300, y = 300 means the prey will move in positive x and positive y direction. 

Please note here that for this grid, point (0,0) lies on the top left corner.  So x = 1, y = 1 will have the prey moving diagonally in down-right direction. 

Let me know if there’s still confusion regarding this.

**Comment by jkker** [comment]
Thanks for clarifying
